
project_id = "sparkstormAI"

[api]
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 5432
major_version = 15

[studio]
port = 3000

[functions.newsletter-confirmation]
verify_jwt = false
